name: Get Kubeconfig for Cloud Kubernetes Cluster
description: Get Kubeconfig for Cloud Kubernetes Cluster
author: everpcpc

inputs:
  provider:
    description: Cloud Provider
    required: true
  cluster-name:
    description: Cluster Name
    required: true
  kubeconfig:
    description: File path to store kubeconfig
    required: true

runs:
  using: node16
  main: dist/index.js

branding:
  icon: message-circle
  color: green
